name: Add Team Member
description: Submit a picture and a discription to be shown on the public website 
title: "[Add Picture]:"
labels: 
assignees:
  - LeonKie
body:
  - type: input
    id: name
    attributes:
      label: Name Details
      description: What it you full Name?
    validations:
      required: true
  - type: textarea
    id: add-picture
    attributes:
      label: Profile Picuture
      description: Add a profile Picture!
      placeholder: Make sure that it is square for ex. 500px x 500px
    validations:
      required: true
  - type: input 
    id: degree
    attributes:
      label: Degree
      description: What are you Studing at the moment?
      paceholder: e.g. M.Sc. Robotics, Cognition, Intelligence
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree that your details can be shown on the public website (enhands.de)
      options:
        - label: I agree
          required: true
