name: Add new Supporter
description: Submit a picture and a discription to be shown on the public website of the new Supporter 
title: "Add Supporter ðŸ–¼ï¸ðŸ‘‹"
labels: "New-Supporter"
assignees:
  - LeonKie
body:
  - type: input
    id: name
    attributes:
      label: '>>Name-Details<<'
      description: What it the full name of the Supporter?
    validations:
      required: true
  - type: textarea
    id: add-picture
    attributes:
      label: '>>Profile-Picture<<'
      description: Add a profile picture!
      placeholder: "Make sure that the logo is as compact as possible. No big boundary!!"
    validations:
      required: true
  - type: dropdown
    id: tier
    attributes:
      label: '>>Tier<<'
      description: What tier is the supporter?
      options:
        - Gold
        - Silber
        - Bronze
      default: 0
    validations:
      required: true
