on:
  issues
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '_-'
          label_marker_end: '-_'

      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
      - name: Output parsed issue
        run: echo ${{ steps.issue-parser.outputs.json }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
