on:
  issues
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub issue forms parser
        id: issue-parser
        uses: edumserrano/github-issue-forms-parser@v1.2.0
        with:
          template-filepath: '.github/ISSUE_TEMPLATE/FROM-NAME.yml'
          issue-form-body: '${{ github.event.issue.body }}'
      # The next step is using powershell to parse the action's output but you can use whatever you prefer.
      # Note that in order to read the step outputs the action step must have an id.
      - name: Output parsed issue
        run: echo ${{ steps.issue-parser.outputs.json }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
