on:
  issues:
    types:
      - labeled
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    if: github.event.label.name == 'New-Supporter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Show parsed data JSON
        run: |
          echo '${{ steps.parse.outputs.payload }}' >> temp.json
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          name: Install dependencies
          run: |
            python -m pip install --upgrade pip
      - run: |
          ls -la
          tree
          python add-supporter.py
          echo "SupporterName=$(cat 'New Supporter')" >> $GITHUB_ENV
          echo "branchName=$(cat 'BranchName')" >> $GITHUB_ENV
      - name: install gh cli
        run: sudo apt install gh
      - name: run git push
        run: |
          git config --global user.name "LeonKie"
          git config --global user.email "leon.kiesgen@web.de"
          git branch "${{ env.branchName }}"
          git checkout "${{ env.branchName }}"
          git add people.json
          git commit -m "⚙ Added ${{ env.SupporterName }} to the Team [BOT]"
          git clean -fd
          git push --set-upstream origin "${{ env.branchName }}"
          git push --force
      - name: gh pr
        run: |
          gh pr create --title "Adding ${{ env.SupporterName }} to the Team" --body "A new Supporter should be added to the website" --head "${{ env.branchName }}"
